### ISSUE TITLE
Cannot read property replace of null

### ISSUE THREAD

**Issue by chrisjpalmer** [npm/hosted-git-info#35]
Hi guys. Trying to run npx on some packages but coming up with this error:

```
npx oclif single book-shelf-app



npx: installed 1 in 1.146s
Path must be a string. Received undefined
npx: installed 427 in 19.507s
C:\Users\chris\AppData\Roaming\npm-cache\_npx\25876\node_modules\oclif\bin\run
'yarn' is not recognized as an internal or external command,
operable program or batch file.
TypeError: Cannot read property 'replace' of null
    at C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/hosted-git-info/index.js:61:63
    at Array.map (<anonymous>)
    at fromUrl (C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/hosted-git-info/index.js:45:39)
    at Function.module.exports.fromUrl (C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/hosted-git-info/index.js:32:18)
    at Object.<anonymous> (C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/normalize-package-data/lib/fixer.js:150:36)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/normalize-package-data/lib/fixer.js:144:31)
    at Array.forEach (<anonymous>)
    at Object.fixDependencies (C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/normalize-package-data/lib/fixer.js:137:41)
    at C:/Users/chris/AppData/Roaming/npm-cache/_npx/25876/node_modules/oclif/node_modules/normalize-package-data/lib/normalize.js:32:38
```

Not sure if the error comes down to this package or not?

Chris

**Comment by Erveon** [comment]
Same issue occurs when creating a fresh project with RC.3 for @vue/cli

**Comment by daviwil** [comment]
I am also seeing this error:

```
2018-07-07T00:32:47.9733690Z TypeError: Cannot read property 'replace' of null
2018-07-07T00:32:47.9761100Z     at /Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/node_modules/hosted-git-info/index.js:61:62
2018-07-07T00:32:47.9786110Z     at Array.map (native)
2018-07-07T00:32:47.9812020Z     at fromUrl (/Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/node_modules/hosted-git-info/index.js:45:39)
2018-07-07T00:32:47.9839880Z     at Function.module.exports.fromUrl (/Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/node_modules/hosted-git-info/index.js:32:18)
2018-07-07T00:32:47.9867370Z     at Install.module.exports.Install.getHostedGitInfo (/Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/lib/install.js:703:28)
2018-07-07T00:32:47.9892320Z     at /Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/lib/install.js:868:34
2018-07-07T00:32:47.9916990Z     at /Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/lib/install.js:922:18
2018-07-07T00:32:47.9942250Z     at iteratee (/Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/lib/install.js:926:16)
2018-07-07T00:32:47.9968170Z     at /Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:227:13
2018-07-07T00:32:47.9993830Z     at iterate (/Users/vsts/agent/2.134.2/work/1/s/apm/node_modules/atom-package-manager/node_modules/async/lib/async.js:134:13)
2018-07-07T00:32:48.0015110Z child_process.js:624
2018-07-07T00:32:48.0033030Z     throw err;
```

**Comment by Erveon** [comment]
I've made a quick PR https://github.com/npm/hosted-git-info/pull/36
Feel free to correct it if it can be done better.

**Comment by daviwil** [comment]
Thanks @iarna and @Erveon for the quick fix!

**Comment by tiandavis** [comment]
Our ember-cli web application was bit by this as well. Thankfully in non-production environments. Thought the problem was with CircleCI initially too. Just wanted to say thanks to everyone who raised the issue and contributed to the PR fix here. 

The Error:

```
Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at /root/project/node_modules/hosted-git-info/index.js:61:63
    at Array.map (<anonymous>)
    at fromUrl (/root/project/node_modules/hosted-git-info/index.js:45:39)
    at Function.module.exports.fromUrl (/root/project/node_modules/hosted-git-info/index.js:32:18)
    at npa (/root/project/node_modules/npm-package-arg/npa.js:78:38)
    at module.exports (/root/project/node_modules/ember-cli/lib/utilities/get-package-base-name.js:13:12)
    at Project.name (/root/project/node_modules/ember-cli/lib/models/project.js:155:12)
    at Project.initializeAddons (/root/project/node_modules/ember-cli/lib/models/project.js:385:50)
    at Project.eachAddonCommand (/root/project/node_modules/ember-cli/lib/models/project.js:451:12)
    at module.exports (/root/project/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
```
